##### Students
GET http://localhost:8080/academics/api/students/pussDest_123/subjects
Accept: application/json
###
POST http://localhost:8080/academics/api/students
Content-Type: application/json
{ "email": "johndoe@mail.com",
 "name": "John Doe",
 "username": "john",
 "password": "jd",
 "courseCode":"1",
 "courseName": "EI"
}