###Sinais biomedicos
#Colestrol

# busca todos os registos
http://localhost:8080/academics/api/biosinais/colestrol/

### busca um registo por id
http://localhost:8080/academics/api/biosinais/colestrol/10

### busca um registo por id de utilizador
http://localhost:8080/academics/api/biosinais/colestrol/0

### cria um registo

POST http://localhost:8080/academics/api/biosinais/colest/create
Content-Type: application/json
{ "id": "10",
  "value": "100",
  "utilizadorNormalID": "0"
}

### atualiza um registo (não precisa de todos os parametros)
PUT http://localhost:8080/academics/api/biosinais/pesagem/101
Content-Type: application/json

{ "id": "101",
  "value": "100",
  "utilizadorNormalID": "0"
}

### apaga um registo

DELETE http://localhost:8080/biosinais/colestrol/10